### ISSUE TITLE
Unable to connect to WebTransport sample client

### ISSUE THREAD

**Issue by kdzapp** [wegylexy/webtransport#1]
Hey @wegylexy -- thanks a ton for making this, was just about to try building my own.

For some reason I can't get it to work. I'm running chrome like this:
`.\chrome.exe --origin-to-force-quic-on=localhost:4433 --ignore-certificate-errors-spki-list={CERT_SPKI} --user-data-dir=.\UserDataDir`

The program runs fine and gives me the certificate hash -- what am I missing? The [chrome example](https://googlechrome.github.io/samples/webtransport/client.html) won't connect.

```
Initiating connection...
Connection failed. WebTransportError: Opening handshake failed.
```

Thank you!

**Comment by wegylexy** [comment]
Since Chrome 100, you don't need to use special command lines, but whitelist the hash of your custom cert in JavaScript directly.
See https://github.com/microsoft/msquic/blob/main/docs/TSG.md#using-a-self-signed-certificate-for-http3

**Comment by kdzapp** [comment]
Thanks Tim! So I’ll have to spin up my own client too?

Kyle Zappitell

Sent via Superhuman iOS ( ***@***.*** )

**Comment by wegylexy** [comment]
You could also F12 to set a break point right after the constructor is invoked and replace it with your own instance that allows your hash.

**Comment by wegylexy** [comment]
![image](https://user-images.githubusercontent.com/8196926/187974596-830cdd1d-a9f0-4d81-9a90-c4f470f39703.png)

**Comment by wegylexy** [comment]
Example:
https://github.com/wegylexy/webtransport/blob/c55d9cc5a11f3a8b8dfd2a12c8d02ad462dc693d/ServerDemo/Program.cs#L24

**Comment by kdzapp** [comment]
That worked! Thank you so much @wegylexy
